
name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'

jobs:
    full-test:
        runs-on: self-hosted

        container:
          image: cuaesd/aesd-autotest:24-assignment5-buildroot
          volumes:
            - /tmp/ssh-sock:/tmp/ssh-sock

        timeout-minutes: 120

        steps:
          - uses: actions/checkout@v2

          - name: Checkout submodules
            run: git submodule update --init --recursive

          - uses: webfactory/ssh-agent@v0.5.3
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          # Crear socket estÃ¡tico accesible por el contenedor
          - name: Prepare SSH socket for container
            run: |
              mkdir -p /tmp/ssh-sock
              ln -sf $SSH_AUTH_SOCK /tmp/ssh-sock/agent.sock
              echo "SSH_AUTH_SOCK=/tmp/ssh-sock/agent.sock" >> $GITHUB_ENV

          # Fix known_hosts dentro del contenedor
          - name: Fix GitHub known_hosts
            run: |
              mkdir -p ~/.ssh
              rm -f ~/.ssh/known_hosts
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              chmod 644 ~/.ssh/known_hosts

          - name: Run full test
            env:
              SSH_AUTH_SOCK: /tmp/ssh-sock/agent.sock
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes"
            run: ./full-test.sh

          - name: Cleanup
            if: always()
            run: ssh-add -D || true
